version: '3.8'

services:
  db:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photoview
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "photoview", "-pphotoview"]
      interval: 5s
      timeout: 5s
      retries: 5

  photoview:
    image: photoview/photoview:latest
    ports:
      - "8081:8080"
    depends_on:
      - db
    volumes:
      - ./test_photos:/photos:ro
      - photoview_cache:/app/cache
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photoview@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=8080
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - PHOTOVIEW_MEDIA_PATH=/photos
      - PHOTOVIEW_ADMIN_PASSWORD=changeme123
      - PHOTOVIEW_ADMIN_USERNAME=admin
    healthcheck:
      test: ["CMD", "mysql", "-h", "db", "-u", "photoview", "-pphotoview", "photoview", "-e", "SELECT COUNT(*) FROM media;"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  photoview_cache:
  db_data: 