version: '3.8'

services:
  db:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photoview
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "photoview", "-pphotoview"]
      interval: 5s
      timeout: 5s
      retries: 5

  photoview:
    image: photoview/photoview:latest
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./Photos:/photos:ro
      - photoview_cache:/app/cache
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photoview@tcp(db:3306)/photoview
      - PHOTOVIEW_LISTEN_PORT=8080
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - PHOTOVIEW_MEDIA_PATH=/photos
      - PHOTOVIEW_DISABLE_FACE_RECOGNITION=true
      - PHOTOVIEW_DISABLE_VIDEO_TRANSCODING=true
      - PHOTOVIEW_DISABLE_RAW_PROCESSING=true

volumes:
  photoview_cache:
  db_data: 