app = "rogers-photo-gallery"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  PHOTOVIEW_LISTEN_IP = "0.0.0.0"
  PHOTOVIEW_LISTEN_PORT = "8080"
  PHOTOVIEW_MEDIA_CACHE = "/app/cache"
  PHOTOVIEW_MEDIA_PATH = "/data/photos"
  PHOTOVIEW_DATABASE_DRIVER = "sqlite"
  PHOTOVIEW_SQLITE_PATH = "/data/photoview.db"
  PHOTOVIEW_INITIAL_SCAN = "true"
  PHOTOVIEW_DISABLE_FACE_RECOGNITION = "1"

[[mounts]]
  source = "photoview_data"
  destination = "/data"

[processes]
  app = "photoview"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "get"
    path = "/api/v1/health"
    protocol = "http"
    tls_skip_verify = true 